"""Tiny dependency-free PDF invoice generator (one A4 page, Helvetica)."""
from datetime import datetime
from decimal import Decimal


def _esc(value: str) -> str:
    text = value.encode("latin-1", errors="replace").decode("latin-1")
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _text(x: int, y: int, size: int, value: str, bold: bool = False) -> str:
    font = "F2" if bold else "F1"
    return f"BT /{font} {size} Tf {x} {y} Td ({_esc(value)}) Tj ET"


def build_invoice(
    shop_name: str,
    number: str,
    created_at: datetime,
    email: str,
    address: str,
    currency: str,
    items: list[tuple[str, str, int, Decimal]],
    total: Decimal,
) -> bytes:
    ops: list[str] = [
        _text(50, 790, 22, shop_name, bold=True),
        _text(50, 765, 14, f"Invoice {number}", bold=True),
        _text(50, 745, 10, f"Date: {created_at:%Y-%m-%d %H:%M} UTC"),
        _text(50, 730, 10, f"Customer: {email}"),
        _text(50, 715, 10, f"Ship to: {address[:90]}"),
        "0.6 w 50 695 m 545 695 l S",
        _text(50, 680, 10, "SKU", bold=True),
        _text(160, 680, 10, "Item", bold=True),
        _text(370, 680, 10, "Qty", bold=True),
        _text(410, 680, 10, "Unit", bold=True),
        _text(480, 680, 10, "Amount", bold=True),
    ]
    y = 660
    for sku, name, qty, unit in items[:28]:
        ops += [
            _text(50, y, 10, sku[:18]),
            _text(160, y, 10, name[:36]),
            _text(370, y, 10, str(qty)),
            _text(410, y, 10, f"{unit:.2f}"),
            _text(480, y, 10, f"{unit * qty:.2f}"),
        ]
        y -= 18
    ops += [
        f"0.6 w 50 {y + 6} m 545 {y + 6} l S",
        _text(380, y - 12, 12, f"Total: {total:.2f} {currency}", bold=True),
        _text(50, 60, 8, "Generated by order-service. Stored in OBS."),
    ]
    stream = "\n".join(ops).encode("latin-1")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
        b"/Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>",
        b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{i} 0 obj\n".encode() + obj + b"\nendobj\n"
    xref = len(out)
    out += f"xref\n0 {len(objects) + 1}\n0000000000 65535 f \n".encode()
    for off in offsets:
        out += f"{off:010d} 00000 n \n".encode()
    out += f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n".encode()
    return bytes(out)
